### ISSUE TITLE
I got some error from ImportError: DLL load failed while importing moving_statistics: The specified module could not be found.

### ISSUE THREAD

**Issue by kamwansiri** [PfizerRD/scikit-digital-health#103]
I want to use Sleep function for predict number of sleep and wake but I got some this error.
File "d:\PPG\Python\RR\cal_RR\Accsleepwake.py", line 11, in <module>
    from skdh.sleep import Sleep
  File "D:\Anaconda\envs\rhodes\lib\site-packages\skdh\__init__.py", line 31, in <module>        
    from skdh import utility
  File "D:\Anaconda\envs\rhodes\lib\site-packages\skdh\utility\__init__.py", line 52, in <module>
    from skdh.utility.math import *
  File "D:\Anaconda\envs\rhodes\lib\site-packages\skdh\utility\math.py", line 9, in <module>     
    from skdh.utility import _extensions
  File "D:\Anaconda\envs\rhodes\lib\site-packages\skdh\utility\_extensions\__init__.py", line 1, in <module>
    from .moving_statistics import (
ImportError: DLL load failed while importing moving_statistics: The specified module could not be found.
Can you help me please, Thank you.

**Comment by kamwansiri** [comment]
with pip. However, I have already change to do my project on google colab but I've got some error on day_ends.
![image](https://github.com/PfizerRD/scikit-digital-health/assets/133620875/d2b222fe-2866-4926-be4b-c72991de7592)
do you have any suggestion for me? Thank you for fast answering

**Comment by kamwansiri** [comment]
Oh, Thank you. day_ends is not depend on number of timestamp or data, alright.

**Comment by kamwansiri** [comment]
> day_ends={(12, 24): (start_index, end_index)}

Do I have any chance to change the day_ends?

**Comment by LukasAdamowicz** [comment]
per the [documentation for sleep](https://scikit-digital-health.readthedocs.io/en/latest/ref/generated/skdh.sleep.Sleep.html#skdh.sleep.Sleep) you can change what indices (ie `(12, 24)` currently) with the `day_ends` parameter when initializing `Sleep`. Though keep in mind the sleep algorithm works best when the sleep windows is roughly centered in the data being provided
