### ISSUE TITLE
Warning message: bad block

### ISSUE THREAD

**Issue by ohspc89** [PfizerRD/scikit-digital-health#107]
Hello,

Thank you for preparing and managing the package. I am trying to read recorded signal from an Ax6 sensor (.cwa file) using ReadCwa.predict()

I got a warning for this one dataset. The message reads:
"""
WARNING: 1 bad blocks
/python3.11/site-packages/skdh/io/axivity.py:136: RuntimeWarning: Bad data blocks present
    fs, n_bad_samples, imudata, ts, temperature, starts, stops = read_axivity(
"""

So I tried to read the same .cwa file using another module: openmovement. I noticed that there's one "block" of 40 points that don't seem to be right. Below is the raw values of X-axis measurement from the sensor.
![Figure_1](https://github.com/PfizerRD/scikit-digital-health/assets/8701529/b95083d0-e26e-452a-b9cb-fa34f775e329)

From sample number 80 to 119, values are 0.0. If you check with the openmovement module, they are actually not 0's.
I noticed that this behavior is present along all three accelerometer axes (X, Y, and Z). May I ask if this has been observed before, or just an issue with this particular file? I can share the cwa file, if needed.

**Comment by LukasAdamowicz** [comment]
The behavior stems from initializing the data to 0s before reading all the data into the arrays (hence why there is a block of 40 samples that is 0).

As to why this happens, that warning is a results of one of 3 things: 
1. The data packet (40 samples in your case) is incorrect;
2. The length of the data packet is saved incorrectly in the file
3. the checksum for the data package (to verify packet integrity) is not summing to the correct value

without seeing the file, I'm unsure as to the issue. If you are able to share the data (feel free to send via email) I can take a look into exactly why this is happening for your case

**Comment by ohspc89** [comment]
Email sent from ohxxx414@umn.edu. Thanks.

**Comment by LukasAdamowicz** [comment]
Closing as an issue with a data block resulting in a non-zero checksum for the data block (40 samples).

**Comment by ohspc89** [comment]
Forgot to say thank you for reviewing this issue. Much appreciated.
