### ISSUE TITLE
Value of Shipping criteria is not checked

### ISSUE THREAD

**Issue by rouzbeh** [PfizerRD/scikit-digital-health#125]
In `AccelThresholdWearDetection`, and contrary to what the documentation says, `shipping_criteria=False` is treated the same as `shipping_criteria=True`

https://github.com/PfizerRD/scikit-digital-health/blob/646c0ddffbd2cde5568d3d2f4203a889cf9bbaf2/src/skdh/preprocessing/wear_detection.py#L752

**Comment by LukasAdamowicz** [comment]
Thanks, this will be fixed in the next release.
