### ISSUE TITLE
How to install this package under Window system

### ISSUE THREAD

**Issue by nie911** [PfizerRD/scikit-digital-health#64]
I don't know if there is something wrong with my installation operation, or this package can't be installed and run under window system at the moment? I would like to ask the authors to answer the questions.

**Comment by Grainger-Sasso** [comment]
I had the same issue on Windows with C compilers failing. My solution was to create a VM to run Ububtu LTS. I installed Python 3.10.4 and latest Anaconda release, created a Conda environment for it (using pycharm) and ran [conda install -c conda-forge scikit-digital-health]. This has resulted in the SKDH package and dependencies being correctly built for me.

**Comment by nie911** [comment]
Yes, I am currently running in Ububtu LTS, but I have modified some of the code because it keeps reporting errors

> I had the same issue on Windows with C compilers failing. My solution was to create a VM to run Ububtu LTS. I installed Python 3.10.4 and latest Anaconda release, created a Conda environment for it (using pycharm) and ran [conda install -c conda-forge scikit-digital-health]. This has resulted in the SKDH package and dependencies being correctly built for me.

**Comment by LukasAdamowicz** [comment]
Windows pre-built wheels are no up on PyPI for version 0.11.6, if you can confirm that this fixes your issues or if you still have errors if this is still relevant.
