### ISSUE TITLE
Issues installing SKDH on Azure Databricks

### ISSUE THREAD

**Issue by sarthak-c** [PfizerRD/scikit-digital-health#65]
Thank you for the wonderful package. I am currently having trouble installing Scikit-Digital-Health on Azure Databricks. I have tried building a wheel file and also tried installing directly via a tarball zip file but both approaches failed. My cluster is currently running Ubuntu 20.04.4 LTS (Focal Fossa) and I get an unable to build wheels error. It would be wonderful if you could please release support on PyPI.

**Comment by LukasAdamowicz** [comment]
@sarthak-c if you are still having issues with this, if you can post the issue that would helpful.

**Comment by sarthak-c** [comment]
Closing this issue as I was able to run on SageMaker.
