### ISSUE TITLE
Reading raw CSV files

### ISSUE THREAD

**Issue by sarthak-c** [PfizerRD/scikit-digital-health#69]
Does the package have a process for reading raw CSV files? Can I add to the SKDH pipeline functionality for reading a raw CSV file with simply 4 columns as time (s or ms), and x, y, and z accelerations in g?

**Comment by LukasAdamowicz** [comment]
Currently there is no built-in functionality for reading raw CSV files. If this is something that would be useful, feel free to submit a PR
