### ISSUE TITLE
AttributeError: module 'skdh' has no attribute 'read'

### ISSUE THREAD

**Issue by hillolsarker** [PfizerRD/scikit-digital-health#70]
Example:
[skdh_examples.ipynb](https://github.com/PfizerRD/scikit-digital-health/blob/main/examples/skdh_examples.ipynb)

Line:
`data = skdh.read.ReadCwa().predict(file="example_data.cwa")`

Exception:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 data = skdh.read.ReadCwa().predict(file="example_data.cwa")

AttributeError: module 'skdh' has no attribute 'read'

**Comment by LukasAdamowicz** [comment]
In version 0.9.10 the `read` module was renamed to `io`. Fixed with 494dd3f6af85738a50393c5f6e4388b0551dd6d5
