### ISSUE TITLE
Gait module failing on IMU data with low sampling rate (25 Hz)

### ISSUE THREAD

**Issue by Grainger-Sasso** [PfizerRD/scikit-digital-health#73]
I have successfully ran the SKDH Gait module on data sampled at 100 Hz. I have recently tried to run the Gait module on data collected from another sensor, one sampling at 25 Hz. The Gait pipeline is failing when running on this low sampling rate data.

The module is failing when trying to instantiate a Scipy filter, iirfilter. The failure is due to critical frequency of the signal (Wn) being outside the acceptable range,  0.0 < Wn < 1.0 (note this range is non-inclusive). The value of Wn is set on line 670 of gait_endpoints.py to be 1.0: 

Wn = 2 * 10 / fs [fs = 20.0 Hz, set from the low frequency downsampling performed prior to this point] 

This causes the butter() method of _filter_design.py to fail: 

iirfilter(N, Wn, btype=btype, analog=analog,
                     output=output, ftype='butter', fs=fs)
Traceback (most recent call last):
  File "/opt/pycharm-community-2022.1.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "scipy/signal/_filter_design.py", line 2518, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

Console output:
skdh/gait/gait.py:477: UserWarning: Frequency is less than 50Hz. Downsampling to 20Hz. Note that this may effect gait endpoints results values
  warn(
skdh/features/lib/smoothness.py:150: RuntimeWarning: divide by zero encountered in log
  return -nplog(abs(res))
skdh/utility/orientation.py:97: UserWarning: Accel. correction angles outside possible range [-1, 1]. Not correcting.
  warn("Accel. correction angles outside possible range [-1, 1]. Not correcting.")
High stride frequency [1.05] results too few harmonics in frequency range. Setting to nan
...
...
...
skdh/gait/gait_endpoints/gait_endpoints.py:600: RuntimeWarning: Mean of empty slice
  psi_abs = nanmean(abs(phase[mask] - 0.5))  # using % not degrees right now
numpy/lib/nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
skdh/gait/gait_endpoints/gait_endpoints.py:601: RuntimeWarning: Mean of empty slice
  psi_cv = nanstd(phase[mask], ddof=1) / nanmean(phase[mask])
Traceback (most recent call last):
  File "/opt/pycharm-community-2022.1.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2022.1.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "", line 410, in <module>
    main()
...
  File "skdh/pipeline.py", line 399, in run
    kwargs, step_result = proc.predict(**kwargs)
  File "skdh/gait/gait.py", line 644, in predict
    param().predict(goal_fs, leg_length, gait, gait_aux)
  File "skdh/gait/gait_endpoints/base.py", line 69, in predict
    self._predict(fs, leg_length, gait, gait_aux)
  File "skdh/gait/gait_endpoints/gait_endpoints.py", line 670, in _predict
    sos = butter(4, 2 * 10 / fs, btype="low", output="sos")
  File "scipy/signal/_filter_design.py", line 3053, in butter
    return iirfilter(N, Wn, btype=btype, analog=analog,
  File "scipy/signal/_filter_design.py", line 2518, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

Process finished with exit code 1

**Comment by LukasAdamowicz** [comment]
I believe this should be fixed with GH-72

If not feel free to re-open
