### ISSUE TITLE
Incorrect variable type 'list' passed to BaseProcess._check_if_idx_none() when run on low sampling rate data, expects 'numpy.ndarray'

### ISSUE THREAD

**Issue by Grainger-Sasso** [PfizerRD/scikit-digital-health#74]
When running IMU data with sampling rate (fs) < 50 Hz through sleep module pipeline, an error is thrown by BaseProcess._check_if_idx_none(). The error is caused by an attempt to slice an input variable [var] of type 'list' with slicing conventions reserved for a variable with type 'numpy.ndarray':

line 113: var[:, 0], var[:, 1]

Error is not thrown on IMU data with fs > 50 Hz. This leads me to believe that some upstream process to BaseProcess._check_if_idx_none() is setting input variable [var] to type 'list' insteam of the intended type 'numpy.ndarray' as indicated in the docstring:

"""
var : {None, numpy.ndarray}
            None, or a 2d ndarray of start and stop indices shape(N, 2).
"""

**Comment by LukasAdamowicz** [comment]
Do you have a MWE for the code for this processing? I'm sure its actually related to the sleep module but instead to how the day_ends array is being passed in
