### ISSUE TITLE
Issue with trimming the CWA files using readCwa()

### ISSUE THREAD

**Issue by bmarzban** [PfizerRD/scikit-digital-health#89]
It's a great package. Thanks for sharing and making it public. 
I have tried to read some CWA files and the package tends to trim the output accelerometer data. For example, we know the input CWA contains 10,000,000 rows/timestamps, but readCWA() generates "accel" of 9,500,000 row/timestamps. Is this a bug or trimming happens for a reason? Thanks.

**Comment by bmarzban** [comment]
On the same note, I actually did a comparison between SKDH and https://github.com/OxWearables.
Sounds like the output "accel" is not actually trimmed in terms of time and rather resampled to a 97- 99 Hz (that is why there are less rows using SKDH). Any suggestions on this? Thanks!

**Comment by LukasAdamowicz** [comment]
The CWA reader does not do any trimming. However I believe there is a slightly different method for timestamp adjustment in the original CWA reader from axivity (also more complicated) that the OxWearables is potentially using. SKDH does not do any resampling of the data when reading, and only reports what the basic timestamps indicate. These timestamps are provided per block of data (30+ samples per block), so you can end up with a calculated sampling frequency not equal to what is set simply by how the interpolation between block timestamps works.

**Comment by bmarzban** [comment]
@LukasAdamowicz Thanks for the response. FYI, I did another compare, with a CWA reader from OPENMOVEMENT package (https://github.com/digitalinteraction/openmovement) and found out that the readCwa() from SKDH outputs the same number of rows as OPENMOVEMENT.  And in-fact the issue rises from https://github.com/OxWearables package, since they assume 100 Hz fixed sampling rate for all the CWA files. Thanks!

**Comment by LukasAdamowicz** [comment]
Thanks for checking, glad to have more evidence that it matches OPENMOVEMENT!
