### ISSUE TITLE
Call to the 'predict' method outputs empty data frame

### ISSUE THREAD

**Issue by sarthak-c** [PfizerRD/scikit-digital-health#91]
I am working with the SKDH gait module and have customized the 'predict' method to work with NumPy arrays containing timestamps, accelerometry, and gyroscope data. The form of function call I am using is

`p = skdh.gait.Gait()`
`predictions = p.predict(time = time, accel = accel, gyro = gyro, height = height)`

For some particular values of accel and gyro, although these NumPy arrays are not empty, I get as a result of the above function call an empty dictionary of predictions which looks like as follows...

<img width="185" alt="image" src="https://user-images.githubusercontent.com/69697071/218507230-61f0d7e1-87fd-420f-9a5f-a2339f74655d.png">

Is there any reason why my function call works perfectly fine for certain values of time, accel, and gyro, but returns an empty dictionary of features for certain other values?

**Comment by LukasAdamowicz** [comment]
With a custom `predict` method I am not sure, as it would be your code that would not be working, depending on how much custom code is in your `predict` method.

**Comment by sarthak-c** [comment]
Oops, sorry for the confusion, I have not changed the SKDH `predict` method at all, it is the same method as the original package. Thanks for reaching out!

**Comment by LukasAdamowicz** [comment]
In that case, can you confirm that there is gait activity in the sections where it outputs empty results?

**Comment by LukasAdamowicz** [comment]
also that acceleration is in units of gravitational acceleration (ie motionless magnitude = 1)

**Comment by sarthak-c** [comment]
The acceleration is in units of g, but can you please let me know how I can confirm gait activity in the data blocks? At first glance, it seems to be that there is no difference between the faulty and non-faulty blocks. Can you please suggest me checks I can perform to confirm?

Thank you so much for your time!

**Comment by LukasAdamowicz** [comment]
other than knowing based on the data and visual inspection, not much to do to check. How long are the blocks of data that you are passing in?

**Comment by sarthak-c** [comment]
60 seconds worth of gait data collected at a sampling frequency of 100 Hz. So the NumPy arrays accel and gyro (as well as time) are of size approximately 6000 at each pass.

**Comment by LukasAdamowicz** [comment]
Interesting, this isn't something I've observed before - any other details you can share about the data (ie from healthy population, etc), or even data or screenshot of the acceleration trace - feel free to reach out via email if you can but don't want it on the issue thread.

**Comment by sarthak-c** [comment]
The faulty blocks of data come from a combination of diseased (PD) and healthy individuals. I am reaching out to you soon over email regarding some sample acceleration traces. I appreciate the help!
